// <auto-generated />
namespace SiteOfMe.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class mignewloock : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mignewloock));
        
        string IMigrationMetadata.Id
        {
            get { return "201306151352474_mig-new-loock"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return Resources.GetString("Source"); }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
